[build]
builder = "dockerfile"
dockerfilePath = "./Dockerfile"
buildCommand = "npm ci && npm run build"

[deploy]
startCommand = "node dist/index.js"
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
numReplicas = 1

[[services]]
name = "medusa-mcp-server"
type = "web"

[services.medusa-mcp-server]
port = 3000
host = "0.0.0.0"